### ISSUE TITLE
Style Guide Questions

### ISSUE THREAD

**Issue by geoffreyyip** [DataKind-DC/homelessness-service-navigator#1]
Do we want `prettier` to auto-format code?
Tabs, 2-spaces, or 4-spaces?
Line length? 
Enable experimental stage-3 `object-rest-spread` syntax?

@chououtside @electricflannel

**Comment by geoffreyyip** [comment]
My preferences in bold

Do we want prettier to auto-format code? **Strong yes. Consistent format makes onboarding easier. Also believe we should install husky. That function like a precommit hook, but controlled through npm scripts.**
Tabs, 2-spaces, or 4-spaces? **Prefer 4 spaces.**
Line length? **No preference.**
Enable experimental stage-3 object-rest-spread syntax? **Strong yes. It plays well with React.**

**Comment by chououtside** [comment]
Do we want prettier to auto-format code? *Yes, I was planning on adding a
linter to incorporate prettier as well when I get the time*
Tabs, 2-spaces, or 4-spaces? *2 Spaces*
Line length? *No Preference*
Enable experimental stage-3 object-rest-spread syntax? *Yes*

**Comment by electricflannel** [comment]
Do we want prettier to auto-format code? Yes
Tabs, 2-spaces, or 4-spaces? 2
Line length? No proference
Enable experimental stage-3 object-rest-spread syntax? Yes

**Comment by electricflannel** [comment]
Also, css/sass/css in js?

**Comment by geoffreyyip** [comment]
@chououtside I found this guide on prettier prelint hooks: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically It could be useful.

@electricflannel Cool with css, or css-in-js. Not feeling sass.

**Comment by geoffreyyip** [comment]
On the four questions and style guide:

About line length, I will mention that we use `prettier` and that `prettier` formats to 80 characters. It's the default and it's their recommended setting.

2-spaces, it is! Right now, the repo has tab characters. But once we install `prettier`, that will go away.

Finally, `object-rest-spread-syntax` needs the babel plugin.
